version: '3.8'

services:
  redis-enterprise:
    image: kurtfm/rs-arm:latest
    platform: linux/arm64
    container_name: redis-enterprise
    tty: true
    cap_add:
      - ALL
    ports:
      # - "10000-19999:10000-19999"
      - "12000:12000"
      - "12001:12001"
      - "9443:9443"
      - "8443:8443"
    networks:
      - radar-network
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost:9443/v1/bootstrap"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

networks:
  radar-network:
    driver: bridge
