version: "3.8"

services:
  redis-enterprise:
    image: kurtfm/rs-arm:latest
    platform: linux/arm64
    container_name: redis-enterprise
    tty: true
    cap_add:
      - ALL
    ports:
      - "12000:12000"
      - "12001:12001"
      - "9443:9443"
      - "8443:8443"
    networks:
      - radar-network
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost:9443/v1/bootstrap"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  # Once we have a published Docker image, we can use this service to auto-initialize
  # redis-enterprise-init:
  #   image: ghcr.io/joshrotenberg/redisctl:latest
  #   container_name: redis-enterprise-init
  #   depends_on:
  #     redis-enterprise:
  #       condition: service_healthy
  #   networks:
  #     - radar-network
  #   environment:
  #     REDIS_ENTERPRISE_URL: "https://redis-enterprise:9443"
  #     REDIS_ENTERPRISE_INSECURE: "true"
  #   command: ["enterprise", "workflow", "init-cluster", "--name", "docker-cluster", "--username", "admin@redis.local", "--password", "Redis123!"]

networks:
  radar-network:
    driver: bridge
