services:
  redis-enterprise:
    image: ${REDIS_ENTERPRISE_IMAGE:-redislabs/redis:latest}
    platform: ${REDIS_ENTERPRISE_PLATFORM:-linux/amd64}
    container_name: redis-enterprise
    tty: true
    cap_add:
      - ALL
    ports:
      - "12000:12000"
      - "12001:12001"
      - "9443:9443"
      - "8443:8443"
    networks:
      - redisctl-network
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost:9443/v1/bootstrap"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  # Auto-initialize Redis Enterprise cluster using our workflow
  # NOTE: Workflow command not yet implemented in CLI
  # Uncomment when enterprise workflow init-cluster is available
  # redis-enterprise-init:
  #   image: joshrotenberg/redisctl:latest
  #   container_name: redis-enterprise-init
  #   depends_on:
  #     redis-enterprise:
  #       condition: service_healthy
  #   networks:
  #     - redisctl-network
  #   environment:
  #     REDIS_ENTERPRISE_URL: "https://redis-enterprise:9443"
  #     REDIS_ENTERPRISE_INSECURE: "true"
  #   command:
  #     [
  #       "enterprise",
  #       "workflow",
  #       "init-cluster",
  #       "--name",
  #       "docker-cluster",
  #       "--username",
  #       "admin@redis.local",
  #       "--password",
  #       "Redis123!",
  #     ]

networks:
  redisctl-network:
    driver: bridge
