# Cargo Release Configuration
# BasedOnly on official cargo-release documentation
# https://github.com/crate-ci/cargo-release/blob/master/docs/reference.mdcontains VALID fields per official documentation

# Branch restrictions
allow-branch = ["main"]

# Git signing (disabled for GitHub Actions)
sign-commit = false
sign-tag = false

# Core settings
push = true
publish = true
verify = true

# Version management
shared-version = true
consolidate-commits = true
dependent-version = "upgrade"

# Consolidate commits when releasing workspace
consolidate-commits = true

# Commit and commit messagetag messages
pre-release-commit-message = "chore: release v{{version}}"

# Tag configuration
tag = true
tag-message = "Release v{{version}}"
tag-name = "v{{version}}"
tag
# Don't create GitHub releases (cargo-dist handles this)
release = false
