# Cargo Release Configuration
# Based on official cargo-release documentation
# https://github.com/crate-ci/cargo-release/blob/master/docs/reference.md

# Only allow releases from main branch
allow-branch = ["main"]

# Don't sign commits/tags (GitHub Actions doesn't have GPG)
sign-commit = false
sign-tag = false

# Push and publish settings
push = true
publish = true
verify = true

# Shared version for all workspace members
shared-version = true

# Consolidate commits when releasing workspace
consolidate-commits = true

# Version bump commit message
pre-release-commit-message = "chore: release v{{version}}"

# Tag configuration
tag = true
tag-message = "Release v{{version}}"
tag-name = "v{{version}}"

# Don't create GitHub releases - cargo-dist will handle that
release = false

# Dependencies between crates - automatically upgrade
dependent-version = "upgrade"
